import SideBar from '@/components/Layout/SideBar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100 flex`} >
        <div className='w-1/4 bg-white hidden md:block'>
        <SideBar />
        </div>
        <div className='w-full md:w-3/4'>
        {children}
        </div>
        </body>
    </html>
  );
}
